server:
	gcc -pthread csapp.c csapp.h  tiny.c -o tinyserver
all:
	gcc -pthread csapp.c csapp.h  tiny.c -o tinyserver
	gcc -pthread adder.c csapp.h -o cgi-bin/adder
	gcc -pthread csapp.c csapp.h delay.c -o cgi-bin/delay
